version: 0.2

env:
  secrets-manager:
    PGHOST: DataWarehouseStackDWSecret9-3cVPSMBS42E4:host
    PGUSER: DataWarehouseStackDWSecret9-3cVPSMBS42E4:username
    PGPASSWORD: DataWarehouseStackDWSecret9-3cVPSMBS42E4:password
    PGPORT: DataWarehouseStackDWSecret9-3cVPSMBS42E4:port
    PGDATABASE: DataWarehouseStackDWSecret9-3cVPSMBS42E4:dbname

phases:
  pre_build:
    commands:
      - echo Preparing to run SQL scripts
  build:
    commands:
      - echo Running SQL scripts in 'schemas' directory
      - find schemas -type f -name "*.sql" -exec psql -f {} \;

      - echo Running SQL scripts in 'tables' directory
      - find tables -type f -name "*.sql" -exec psql -f {} \;

      - echo Running SQL scripts in 'stored procedures' directory
      - find procedures -type f -name "*.sql" -exec psql -f {} \;

      - echo Running SQL scripts in 'views' directory
      - find views -type f -name "*.sql" -exec psql -f {} \;

      - echo Running SQL scripts in 'schedules' directory
      - find schedules -type f -name "*.sql" -exec psql -f {} \;

      - echo SQL script execution finished!
