CREATE OR REPLACE PROCEDURE load_weekly_player_stats()
LANGUAGE plpgsql
AS $$
BEGIN

INSERT INTO players.weekly_regular_season_stats (
    player_id,
    player_name,
    player_display_name,
    position_group,
    season,
    week,
    completions,
    attempts,
    passing_yards,
    passing_tds,
    interceptions,
    sacks,
    sack_yards,
    sack_fumbles,
    sack_fumbles_lost,
    passing_air_yards,
    passing_yards_after_catch,
    passing_first_downs,
    passing_epa,
    passing_2pt_conversions,
    carries,
    rushing_yards,
    rushing_tds,
    rushing_fumbles,
    rushing_fumbles_lost,
    rushing_first_downs,
    rushing_epa,
    rushing_2pt_conversions,
    receptions,
    targets,
    receiving_yards,
    receiving_tds,
    receiving_fumbles,
    receiving_fumbles_lost,
    receiving_air_yards,
    receiving_yards_after_catch,
    receiving_first_downs,
    receiving_epa,
    receiving_2pt_conversions,
    target_share,
    air_yards_share,
    special_teams_tds,
    fantasy_points,
    fantasy_points_ppr
)
SELECT
    w.player_id,
    p.display_name AS player_name,
    p.display_name AS player_display_name,
    p.position_group,
    w.season,
    w.week,
    w.completions,
    w.attempts,
    w.passing_yards,
    w.passing_tds,
    w.passing_interceptions AS interceptions,
    w.sacks_suffered AS sacks,
    w.sack_yards_lost AS sack_yards,
    w.sack_fumbles,
    w.sack_fumbles_lost,
    w.passing_air_yards,
    w.passing_yards_after_catch,
    w.passing_first_downs,
    w.passing_epa,
    w.passing_2pt_conversions,
    w.carries,
    w.rushing_yards,
    w.rushing_tds,
    w.rushing_fumbles,
    w.rushing_fumbles_lost,
    w.rushing_first_downs,
    w.rushing_epa,
    w.rushing_2pt_conversions,
    w.receptions,
    w.targets,
    w.receiving_yards,
    w.receiving_tds,
    w.receiving_fumbles,
    w.receiving_fumbles_lost,
    w.receiving_air_yards,
    w.receiving_yards_after_catch,
    w.receiving_first_downs,
    w.receiving_epa,
    w.receiving_2pt_conversions,
    w.target_share,
    w.air_yards_share,
    w.special_teams_tds,
    w.fantasy_points,
    w.fantasy_points_ppr
FROM raw.weekly w
JOIN raw.players p ON p.gsis_id = w.player_id
WHERE w.season_type = 'REG'
  AND p.position_group IN ('QB', 'WR', 'RB', 'TE', 'K')
ON CONFLICT (player_id, season, week) DO NOTHING;

INSERT INTO players.weekly_postseason_stats (
    player_id,
    player_name,
    player_display_name,
    position_group,
    season,
    week,
    completions,
    attempts,
    passing_yards,
    passing_tds,
    interceptions,
    sacks,
    sack_yards,
    sack_fumbles,
    sack_fumbles_lost,
    passing_air_yards,
    passing_yards_after_catch,
    passing_first_downs,
    passing_epa,
    passing_2pt_conversions,
    carries,
    rushing_yards,
    rushing_tds,
    rushing_fumbles,
    rushing_fumbles_lost,
    rushing_first_downs,
    rushing_epa,
    rushing_2pt_conversions,
    receptions,
    targets,
    receiving_yards,
    receiving_tds,
    receiving_fumbles,
    receiving_fumbles_lost,
    receiving_air_yards,
    receiving_yards_after_catch,
    receiving_first_downs,
    receiving_epa,
    receiving_2pt_conversions,
    target_share,
    air_yards_share,
    special_teams_tds,
    fantasy_points,
    fantasy_points_ppr
)
SELECT
    w.player_id,
    p.display_name AS player_name,
    p.display_name AS player_display_name,
    p.position_group,
    w.season,
    w.week,
    w.completions,
    w.attempts,
    w.passing_yards,
    w.passing_tds,
    w.passing_interceptions AS interceptions,
    w.sacks_suffered AS sacks,
    w.sack_yards_lost AS sack_yards,
    w.sack_fumbles,
    w.sack_fumbles_lost,
    w.passing_air_yards,
    w.passing_yards_after_catch,
    w.passing_first_downs,
    w.passing_epa,
    w.passing_2pt_conversions,
    w.carries,
    w.rushing_yards,
    w.rushing_tds,
    w.rushing_fumbles,
    w.rushing_fumbles_lost,
    w.rushing_first_downs,
    w.rushing_epa,
    w.rushing_2pt_conversions,
    w.receptions,
    w.targets,
    w.receiving_yards,
    w.receiving_tds,
    w.receiving_fumbles,
    w.receiving_fumbles_lost,
    w.receiving_air_yards,
    w.receiving_yards_after_catch,
    w.receiving_first_downs,
    w.receiving_epa,
    w.receiving_2pt_conversions,
    w.target_share,
    w.air_yards_share,
    w.special_teams_tds,
    w.fantasy_points,
    w.fantasy_points_ppr
FROM raw.weekly w
JOIN raw.players p ON p.gsis_id = w.player_id
WHERE w.season_type = 'POST'
  AND p.position_group IN ('QB', 'WR', 'RB', 'TE', 'K')
ON CONFLICT (player_id, season, week) DO NOTHING;

END;
$$;
