CREATE TABLE IF NOT EXISTS players.player_ids (
	mfl_id int8 NULL,
	sportradar_id text NULL,
	fantasypros_id text NULL,
	gsis_id text NULL,
	pff_id text NULL,
	sleeper_id text NULL,
	nfl_id text NULL,
	espn_id text NULL,
	yahoo_id text NULL,
	fleaflicker_id text NULL,
	cbs_id text NULL,
	pfr_id text NULL,
	cfbref_id text NULL,
	rotowire_id text NULL,
	rotoworld_id text NULL,
	ktc_id text NULL,
	stats_id text NULL,
	stats_global_id text NULL,
	fantasy_data_id text NULL,
	swish_id text NULL,
	"name" text NULL,
	merge_name text NULL,
	"position" text NULL,
	team text NULL,
	birthdate timestamp NULL,
	age int NULL,
	draft_year int8 NULL,
	draft_round int8 NULL,
	draft_pick int8 NULL,
	draft_ovr int8 NULL,
	twitter_username text NULL,
	height text NULL,
	weight int8 NULL,
	college text NULL,
	db_season int8 NULL
);

